version: '3.8'

volumes:
  database:

services:
  api_ghibli_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_db
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 5672:5672
      - 25672:25672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=ghibliapi
      - RABBITMQ_DEFAULT_PASS=ghibliapi